"""Adicionando restrição de integridade em InstrucaoMidia

Revision ID: 5534d5e250e1
Revises: 7af071c7942e
Create Date: 2026-07-14 12:24:14.134863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5534d5e250e1'
down_revision: Union[str, Sequence[str], None] = '7af071c7942e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('instrucao_midia_ibfk_1'), 'instrucao_midia', type_='foreignkey')
    op.drop_constraint(op.f('instrucao_midia_ibfk_2'), 'instrucao_midia', type_='foreignkey')
    op.create_foreign_key(None, 'instrucao_midia', 'midia', ['midia_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'instrucao_midia', 'instrucao', ['instrucao_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instrucao_midia', type_='foreignkey')
    op.drop_constraint(None, 'instrucao_midia', type_='foreignkey')
    op.create_foreign_key(op.f('instrucao_midia_ibfk_2'), 'instrucao_midia', 'midia', ['midia_id'], ['id'])
    op.create_foreign_key(op.f('instrucao_midia_ibfk_1'), 'instrucao_midia', 'instrucao', ['instrucao_id'], ['id'])
    # ### end Alembic commands ###
