"""Reajustando integridades em Instrucao e Midia

Revision ID: 65f5052b671b
Revises: baafc82df56e
Create Date: 2026-07-15 11:03:09.024996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f5052b671b'
down_revision: Union[str, Sequence[str], None] = 'baafc82df56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
