"""Adicionando nova coluna em InstrucaoMidia

Revision ID: 7af071c7942e
Revises: df4182b0a2f3
Create Date: 2026-07-10 10:56:41.118136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af071c7942e'
down_revision: Union[str, Sequence[str], None] = 'df4182b0a2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrucao_midia', sa.Column('ordem_exibicao', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrucao_midia', 'ordem_exibicao')
    # ### end Alembic commands ###
