"""Testando migração inicial

Revision ID: a01345f1e507
Revises: 
Create Date: 2026-07-02 13:44:28.339356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01345f1e507'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('midia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=255), nullable=True),
    sa.Column('legenda', sa.String(length=150), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caminho_arquivo')
    )
    op.create_table('nivel_acesso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('publico', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nivel_acesso_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nivel_acesso_id'], ['nivel_acesso.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('instrucao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('nivel_acesso_id', sa.Integer(), nullable=False),
    sa.Column('usuario_atualizou_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('url_apoio', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nivel_acesso_id'], ['nivel_acesso.id'], ),
    sa.ForeignKeyConstraint(['usuario_atualizou_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrucao_midia',
    sa.Column('instrucao_id', sa.Integer(), nullable=False),
    sa.Column('midia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrucao_id'], ['instrucao.id'], ),
    sa.ForeignKeyConstraint(['midia_id'], ['midia.id'], ),
    sa.PrimaryKeyConstraint('instrucao_id', 'midia_id')
    )
    op.create_table('instrucao_topico',
    sa.Column('instrucao_id', sa.Integer(), nullable=False),
    sa.Column('topico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrucao_id'], ['instrucao.id'], ),
    sa.ForeignKeyConstraint(['topico_id'], ['topico.id'], ),
    sa.PrimaryKeyConstraint('instrucao_id', 'topico_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrucao_topico')
    op.drop_table('instrucao_midia')
    op.drop_table('instrucao')
    op.drop_table('usuario')
    op.drop_table('topico')
    op.drop_table('nivel_acesso')
    op.drop_table('midia')
    # ### end Alembic commands ###
