"""Adicionando índice FULLTEXT em Instrucao

Revision ID: b8b98747c1c9
Revises: 5534d5e250e1
Create Date: 2026-07-14 12:53:41.554548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b98747c1c9'
down_revision: Union[str, Sequence[str], None] = '5534d5e250e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_instrucao_busca', 'instrucao', ['titulo', 'conteudo'], unique=False, mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_instrucao_busca', table_name='instrucao', mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###
