"""Reajustando índices FULLTEXT em Instrucao

Revision ID: baafc82df56e
Revises: b8b98747c1c9
Create Date: 2026-07-15 10:38:29.543598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baafc82df56e'
down_revision: Union[str, Sequence[str], None] = 'b8b98747c1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_instrucao_busca'), table_name='instrucao', mysql_prefix='FULLTEXT')
    op.create_index('idx_instrucao_conteudo', 'instrucao', ['conteudo'], unique=False, mysql_prefix='FULLTEXT')
    op.create_index('idx_instrucao_titulo', 'instrucao', ['titulo'], unique=False, mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_instrucao_titulo', table_name='instrucao', mysql_prefix='FULLTEXT')
    op.drop_index('idx_instrucao_conteudo', table_name='instrucao', mysql_prefix='FULLTEXT')
    op.create_index(op.f('idx_instrucao_busca'), 'instrucao', ['titulo', 'conteudo'], unique=False, mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###
