"""Aplicando cascade real

Revision ID: df4182b0a2f3
Revises: 1127dbecc899
Create Date: 2026-07-09 13:41:34.591134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4182b0a2f3'
down_revision: Union[str, Sequence[str], None] = '1127dbecc899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('instrucao_topico_ibfk_2'), 'instrucao_topico', type_='foreignkey')
    op.drop_constraint(op.f('instrucao_topico_ibfk_1'), 'instrucao_topico', type_='foreignkey')
    op.create_foreign_key(None, 'instrucao_topico', 'topico', ['topico_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'instrucao_topico', 'instrucao', ['instrucao_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instrucao_topico', type_='foreignkey')
    op.drop_constraint(None, 'instrucao_topico', type_='foreignkey')
    op.create_foreign_key(op.f('instrucao_topico_ibfk_1'), 'instrucao_topico', 'instrucao', ['instrucao_id'], ['id'])
    op.create_foreign_key(op.f('instrucao_topico_ibfk_2'), 'instrucao_topico', 'topico', ['topico_id'], ['id'])
    # ### end Alembic commands ###
